// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TcgWorld.Api.Data;

#nullable disable

namespace TcgWorld.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Annonce", b =>
                {
                    b.Property<int>("IdAnnonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnnonce"));

                    b.Property<DateTime>("AnnDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AnnDateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnnDescription")
                        .HasColumnType("text");

                    b.Property<bool>("AnnFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnnFlgMiseEnAvant")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AnnPrix")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("AnnQuantite")
                        .HasColumnType("integer");

                    b.Property<string>("AnnStatut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdCarte")
                        .HasColumnType("integer");

                    b.Property<int?>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLangue")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.HasKey("IdAnnonce");

                    b.HasIndex("AnnStatut");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdLangue");

                    b.HasIndex("IdPersonne");

                    b.ToTable("datAnnonce", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.AnnonceCarte", b =>
                {
                    b.Property<int>("IdAnnonceCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnnonceCarte"));

                    b.Property<string>("AncEtat")
                        .HasColumnType("text");

                    b.Property<bool>("AncFlgEdition1")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgGrade")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgHolo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgMisscut")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgMissprint")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgPokeball")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgReverse")
                        .HasColumnType("boolean");

                    b.Property<bool>("AncFlgStamp")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("AncNoteGradation")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSocieteGradation")
                        .HasColumnType("integer");

                    b.HasKey("IdAnnonceCarte");

                    b.HasIndex("IdAnnonce")
                        .IsUnique();

                    b.HasIndex("IdSocieteGradation");

                    b.ToTable("datAnnonceCarte", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Bloc", b =>
                {
                    b.Property<int>("IdBloc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBloc"));

                    b.Property<DateOnly?>("BlcDateSortie")
                        .HasColumnType("date");

                    b.Property<string>("BlcNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdJeu")
                        .HasColumnType("integer");

                    b.HasKey("IdBloc");

                    b.HasIndex("IdJeu");

                    b.ToTable("datBloc", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Carte", b =>
                {
                    b.Property<int>("IdCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarte"));

                    b.Property<string>("CrtCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CrtDateSortie")
                        .HasColumnType("date");

                    b.Property<bool>("CrtFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("CrtImage")
                        .HasColumnType("text");

                    b.Property<string>("CrtNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CrtNumero")
                        .HasColumnType("text");

                    b.Property<string>("CrtNumeroSerie")
                        .HasColumnType("text");

                    b.Property<string>("CrtRarete")
                        .HasColumnType("text");

                    b.Property<int>("IdSerie")
                        .HasColumnType("integer");

                    b.HasKey("IdCarte");

                    b.HasIndex("CrtNom");

                    b.HasIndex("IdSerie");

                    b.ToTable("datCarte", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Collection", b =>
                {
                    b.Property<int>("IdCollection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCollection"));

                    b.Property<DateTime>("ColDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ColDateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.HasKey("IdCollection");

                    b.HasIndex("IdPersonne");

                    b.ToTable("datCollection", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CollectionCarte", b =>
                {
                    b.Property<int>("IdCollectionCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCollectionCarte"));

                    b.Property<DateTime>("ColcDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ColcDateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ColcEtat")
                        .HasColumnType("text");

                    b.Property<bool>("ColcFlgEdition1")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgGrade")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgHolo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgMisscut")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgMissprint")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgPokeball")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgReverse")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColcFlgStamp")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ColcNoteGradation")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("ColcQuantite")
                        .HasColumnType("integer");

                    b.Property<int>("IdCarte")
                        .HasColumnType("integer");

                    b.Property<int>("IdCollection")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLangue")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSocieteGradation")
                        .HasColumnType("integer");

                    b.HasKey("IdCollectionCarte");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdCollection");

                    b.HasIndex("IdLangue");

                    b.HasIndex("IdSocieteGradation");

                    b.ToTable("datCollectionCarte", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CollectionItem", b =>
                {
                    b.Property<int>("IdCollectionItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCollectionItem"));

                    b.Property<DateTime>("CliDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CliDateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CliEtat")
                        .HasColumnType("text");

                    b.Property<int>("CliQuantite")
                        .HasColumnType("integer");

                    b.Property<int>("IdCollection")
                        .HasColumnType("integer");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLangue")
                        .HasColumnType("integer");

                    b.HasKey("IdCollectionItem");

                    b.HasIndex("IdCollection");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdLangue");

                    b.ToTable("datCollectionItem", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<string>("CmdAdresse")
                        .HasColumnType("text");

                    b.Property<string>("CmdCodePostal")
                        .HasColumnType("text");

                    b.Property<DateTime>("CmdDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CmdDateExpedition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CmdDateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CmdDateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CmdFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CmdFraisLivraison")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("CmdFraisService")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("CmdMontantTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("CmdPays")
                        .HasColumnType("text");

                    b.Property<string>("CmdVille")
                        .HasColumnType("text");

                    b.Property<int>("IdAcheteur")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatutCommande")
                        .HasColumnType("integer");

                    b.Property<int>("IdVendeur")
                        .HasColumnType("integer");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdAcheteur");

                    b.HasIndex("IdStatutCommande");

                    b.HasIndex("IdVendeur");

                    b.ToTable("datCommande", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CommandeLigne", b =>
                {
                    b.Property<int>("IdCommandeLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommandeLigne"));

                    b.Property<DateTime>("CmlDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CmlMontantTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("CmlPrixUnitaire")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("CmlQuantite")
                        .HasColumnType("integer");

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer");

                    b.HasKey("IdCommandeLigne");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdCommande");

                    b.ToTable("datCommandeLigne", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Conversation", b =>
                {
                    b.Property<int>("IdConversation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConversation"));

                    b.Property<DateTime>("ConDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCommande")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEnchere")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneAcheteur")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneVendeur")
                        .HasColumnType("integer");

                    b.HasKey("IdConversation");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdEnchere");

                    b.HasIndex("IdPersonneAcheteur");

                    b.HasIndex("IdPersonneVendeur");

                    b.ToTable("datConversation", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Enchere", b =>
                {
                    b.Property<int>("IdEnchere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnchere"));

                    b.Property<DateTime?>("EncDateCloture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EncDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EncDateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EncDateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncDescription")
                        .HasColumnType("text");

                    b.Property<bool>("EncFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("EncPrixDepart")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("EncPrixFinal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("EncPrixReserve")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("EncStatut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdCarte")
                        .HasColumnType("integer");

                    b.Property<int?>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int?>("IdLangue")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.Property<int?>("IdPersonneGagnant")
                        .HasColumnType("integer");

                    b.HasKey("IdEnchere");

                    b.HasIndex("EncDateFin");

                    b.HasIndex("EncStatut");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdLangue");

                    b.HasIndex("IdPersonne");

                    b.HasIndex("IdPersonneGagnant");

                    b.ToTable("datEnchere", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.EnchereCarte", b =>
                {
                    b.Property<int>("IdEnchereCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnchereCarte"));

                    b.Property<string>("EncEtat")
                        .HasColumnType("text");

                    b.Property<bool>("EncFlgEdition1")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgGrade")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgHolo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgMisscut")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgMissprint")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgPokeball")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgReverse")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncFlgStamp")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("EncNoteGradation")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("IdEnchere")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSocieteGradation")
                        .HasColumnType("integer");

                    b.HasKey("IdEnchereCarte");

                    b.HasIndex("IdEnchere")
                        .IsUnique();

                    b.HasIndex("IdSocieteGradation");

                    b.ToTable("datEnchereCarte", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Evaluation", b =>
                {
                    b.Property<int>("IdEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluation"));

                    b.Property<string>("EvaCommentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("EvaDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EvaFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<int>("EvaNote")
                        .HasColumnType("integer");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneAuteur")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneEvaluee")
                        .HasColumnType("integer");

                    b.HasKey("IdEvaluation");

                    b.HasIndex("IdPersonneAuteur");

                    b.HasIndex("IdPersonneEvaluee");

                    b.HasIndex("IdCommande", "IdPersonneAuteur")
                        .IsUnique();

                    b.ToTable("datEvaluation", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Expedition", b =>
                {
                    b.Property<int>("IdExpedition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExpedition"));

                    b.Property<DateTime?>("ExpDateExpedition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpDateLivraison")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpDateLivraisonPrevue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExpFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ExpFraisLivraison")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ExpModeLivraison")
                        .HasColumnType("text");

                    b.Property<string>("ExpNumeroSuivi")
                        .HasColumnType("text");

                    b.Property<string>("ExpStatut")
                        .HasColumnType("text");

                    b.Property<string>("ExpTransporteur")
                        .HasColumnType("text");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer");

                    b.HasKey("IdExpedition");

                    b.HasIndex("IdCommande")
                        .IsUnique();

                    b.ToTable("datExpedition", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItem"));

                    b.Property<int>("IdSerie")
                        .HasColumnType("integer");

                    b.Property<int>("IdTypeItem")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ItmDateSortie")
                        .HasColumnType("date");

                    b.Property<bool>("ItmFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItmImage")
                        .HasColumnType("text");

                    b.Property<string>("ItmNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItmNumero")
                        .HasColumnType("text");

                    b.HasKey("IdItem");

                    b.HasIndex("IdSerie");

                    b.HasIndex("IdTypeItem");

                    b.ToTable("datItem", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Jeu", b =>
                {
                    b.Property<int>("IdJeu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJeu"));

                    b.Property<string>("JeuNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdJeu");

                    b.ToTable("datJeu", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Langue", b =>
                {
                    b.Property<int>("IdLangue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLangue"));

                    b.Property<string>("LngCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LngFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("LngNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLangue");

                    b.ToTable("datLangue", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<int>("IdConversation")
                        .HasColumnType("integer");

                    b.Property<int?>("IdOffrePrix")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneExpediteur")
                        .HasColumnType("integer");

                    b.Property<string>("MsgContenu")
                        .HasColumnType("text");

                    b.Property<DateTime>("MsgDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MsgImage")
                        .HasColumnType("text");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdOffrePrix");

                    b.HasIndex("IdPersonneExpediteur");

                    b.ToTable("datMessage", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.MiseEnchere", b =>
                {
                    b.Property<int>("IdMiseEnchere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMiseEnchere"));

                    b.Property<int>("IdEnchere")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MisFlgGagnante")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MisMontant")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("IdMiseEnchere");

                    b.HasIndex("IdEnchere");

                    b.HasIndex("IdPersonne");

                    b.ToTable("datMiseEnchere", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.OffrePrix", b =>
                {
                    b.Property<int>("IdOffrePrix")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOffrePrix"));

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<int?>("IdConversation")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneAcheteur")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonneVendeur")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OfrDateAcceptation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfrDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OfrDateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OfrDateUtilisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OfrMontant")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("OfrStatut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdOffrePrix");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdPersonneAcheteur");

                    b.HasIndex("IdPersonneVendeur");

                    b.HasIndex("OfrStatut");

                    b.ToTable("datOffrePrix", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPanier"));

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PnrDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PnrDateModification")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdPersonne");

                    b.ToTable("datPanier", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PanierLigne", b =>
                {
                    b.Property<int>("IdPanierLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPanierLigne"));

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<int>("IdPanier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PnlDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PnlPrixUnitaire")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("PnlQuantite")
                        .HasColumnType("integer");

                    b.HasKey("IdPanierLigne");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdPanier");

                    b.ToTable("datPanierLigne", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Personne", b =>
                {
                    b.Property<int>("IdPersonne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersonne"));

                    b.Property<string>("PrsAdresse")
                        .HasColumnType("text");

                    b.Property<string>("PrsCodePostal")
                        .HasColumnType("text");

                    b.Property<DateTime>("PrsDateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PrsDateDerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("PrsDateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("PrsEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrsFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrsFlgCompteVerifie")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrsFlgEmailVerifie")
                        .HasColumnType("boolean");

                    b.Property<string>("PrsMotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrsNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrsPays")
                        .HasColumnType("text");

                    b.Property<string>("PrsPrenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrsPseudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrsRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrsTelephone")
                        .HasColumnType("text");

                    b.Property<string>("PrsVille")
                        .HasColumnType("text");

                    b.HasKey("IdPersonne");

                    b.HasIndex("PrsEmail")
                        .IsUnique();

                    b.HasIndex("PrsPseudo")
                        .IsUnique();

                    b.ToTable("datPersonne", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PhotoAnnonce", b =>
                {
                    b.Property<int>("IdPhotoAnnonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhotoAnnonce"));

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("integer");

                    b.Property<string>("PhoChemin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PhoDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PhoFlgPrincipale")
                        .HasColumnType("boolean");

                    b.Property<int?>("PhoOrdre")
                        .HasColumnType("integer");

                    b.HasKey("IdPhotoAnnonce");

                    b.HasIndex("IdAnnonce");

                    b.ToTable("datPhotoAnnonce", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PhotoEnchere", b =>
                {
                    b.Property<int>("IdPhotoEnchere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhotoEnchere"));

                    b.Property<int>("IdEnchere")
                        .HasColumnType("integer");

                    b.Property<string>("PheChemin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PheDateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PheFlgPrincipale")
                        .HasColumnType("boolean");

                    b.Property<int?>("PheOrdre")
                        .HasColumnType("integer");

                    b.HasKey("IdPhotoEnchere");

                    b.HasIndex("IdEnchere");

                    b.ToTable("datPhotoEnchere", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Serie", b =>
                {
                    b.Property<int>("IdSerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSerie"));

                    b.Property<int>("IdBloc")
                        .HasColumnType("integer");

                    b.Property<string>("SerCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SerDateSortie")
                        .HasColumnType("date");

                    b.Property<string>("SerNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSerie");

                    b.HasIndex("IdBloc");

                    b.ToTable("datSerie", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.SocieteGradation", b =>
                {
                    b.Property<int>("IdSocieteGradation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSocieteGradation"));

                    b.Property<string>("SgrCode")
                        .HasColumnType("text");

                    b.Property<bool>("SgrFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("SgrNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSocieteGradation");

                    b.ToTable("datSocieteGradation", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.StatutCommande", b =>
                {
                    b.Property<int>("IdStatutCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStatutCommande"));

                    b.Property<string>("StcCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StcFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("StcNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StcOrdre")
                        .HasColumnType("integer");

                    b.HasKey("IdStatutCommande");

                    b.HasIndex("StcCode")
                        .IsUnique();

                    b.ToTable("datStatutCommande", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.TypeItem", b =>
                {
                    b.Property<int>("IdTypeItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeItem"));

                    b.Property<string>("TypCode")
                        .HasColumnType("text");

                    b.Property<bool>("TypFlgArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("TypNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTypeItem");

                    b.ToTable("datTypeItem", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.VueRecente", b =>
                {
                    b.Property<int>("IdVueRecente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVueRecente"));

                    b.Property<int?>("IdCarte")
                        .HasColumnType("integer");

                    b.Property<int?>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VrcDateVue")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdVueRecente");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdPersonne");

                    b.ToTable("datVueRecente", (string)null);
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Annonce", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Carte", "Carte")
                        .WithMany()
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Langue", "Langue")
                        .WithMany()
                        .HasForeignKey("IdLangue")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carte");

                    b.Navigation("Item");

                    b.Navigation("Langue");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.AnnonceCarte", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithOne("AnnonceCarte")
                        .HasForeignKey("TcgWorld.Api.Data.Entities.AnnonceCarte", "IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.SocieteGradation", "SocieteGradation")
                        .WithMany()
                        .HasForeignKey("IdSocieteGradation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Annonce");

                    b.Navigation("SocieteGradation");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Bloc", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Jeu", "Jeu")
                        .WithMany("Blocs")
                        .HasForeignKey("IdJeu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jeu");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Carte", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Serie", "Serie")
                        .WithMany("Cartes")
                        .HasForeignKey("IdSerie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Collection", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CollectionCarte", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Carte", "Carte")
                        .WithMany()
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Collection", "Collection")
                        .WithMany("Cartes")
                        .HasForeignKey("IdCollection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Langue", "Langue")
                        .WithMany()
                        .HasForeignKey("IdLangue")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.SocieteGradation", "SocieteGradation")
                        .WithMany()
                        .HasForeignKey("IdSocieteGradation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carte");

                    b.Navigation("Collection");

                    b.Navigation("Langue");

                    b.Navigation("SocieteGradation");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CollectionItem", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("IdCollection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Langue", "Langue")
                        .WithMany()
                        .HasForeignKey("IdLangue")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collection");

                    b.Navigation("Item");

                    b.Navigation("Langue");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Commande", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Acheteur")
                        .WithMany()
                        .HasForeignKey("IdAcheteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.StatutCommande", "StatutCommande")
                        .WithMany()
                        .HasForeignKey("IdStatutCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Vendeur")
                        .WithMany()
                        .HasForeignKey("IdVendeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acheteur");

                    b.Navigation("StatutCommande");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.CommandeLigne", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithMany()
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Conversation", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithMany()
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Enchere", "Enchere")
                        .WithMany()
                        .HasForeignKey("IdEnchere")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneAcheteur")
                        .WithMany()
                        .HasForeignKey("IdPersonneAcheteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneVendeur")
                        .WithMany()
                        .HasForeignKey("IdPersonneVendeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Commande");

                    b.Navigation("Enchere");

                    b.Navigation("PersonneAcheteur");

                    b.Navigation("PersonneVendeur");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Enchere", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Carte", "Carte")
                        .WithMany()
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Langue", "Langue")
                        .WithMany()
                        .HasForeignKey("IdLangue")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneGagnant")
                        .WithMany()
                        .HasForeignKey("IdPersonneGagnant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carte");

                    b.Navigation("Item");

                    b.Navigation("Langue");

                    b.Navigation("Personne");

                    b.Navigation("PersonneGagnant");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.EnchereCarte", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Enchere", "Enchere")
                        .WithOne("EnchereCarte")
                        .HasForeignKey("TcgWorld.Api.Data.Entities.EnchereCarte", "IdEnchere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.SocieteGradation", "SocieteGradation")
                        .WithMany()
                        .HasForeignKey("IdSocieteGradation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Enchere");

                    b.Navigation("SocieteGradation");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Evaluation", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Commande", "Commande")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneAuteur")
                        .WithMany()
                        .HasForeignKey("IdPersonneAuteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneEvaluee")
                        .WithMany()
                        .HasForeignKey("IdPersonneEvaluee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("PersonneAuteur");

                    b.Navigation("PersonneEvaluee");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Expedition", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Commande", "Commande")
                        .WithOne("Expedition")
                        .HasForeignKey("TcgWorld.Api.Data.Entities.Expedition", "IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Item", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Serie", "Serie")
                        .WithMany("Items")
                        .HasForeignKey("IdSerie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.TypeItem", "TypeItem")
                        .WithMany("Items")
                        .HasForeignKey("IdTypeItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Serie");

                    b.Navigation("TypeItem");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Message", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.OffrePrix", "OffrePrix")
                        .WithMany("Messages")
                        .HasForeignKey("IdOffrePrix")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneExpediteur")
                        .WithMany()
                        .HasForeignKey("IdPersonneExpediteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("OffrePrix");

                    b.Navigation("PersonneExpediteur");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.MiseEnchere", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Enchere", "Enchere")
                        .WithMany("Mises")
                        .HasForeignKey("IdEnchere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enchere");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.OffrePrix", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithMany()
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Conversation", "Conversation")
                        .WithMany("OffresPrix")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneAcheteur")
                        .WithMany()
                        .HasForeignKey("IdPersonneAcheteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "PersonneVendeur")
                        .WithMany()
                        .HasForeignKey("IdPersonneVendeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Conversation");

                    b.Navigation("PersonneAcheteur");

                    b.Navigation("PersonneVendeur");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Panier", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PanierLigne", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithMany()
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgWorld.Api.Data.Entities.Panier", "Panier")
                        .WithMany("Lignes")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PhotoAnnonce", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Annonce", "Annonce")
                        .WithMany("Photos")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.PhotoEnchere", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Enchere", "Enchere")
                        .WithMany("Photos")
                        .HasForeignKey("IdEnchere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enchere");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Serie", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Bloc", "Bloc")
                        .WithMany("Series")
                        .HasForeignKey("IdBloc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bloc");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.VueRecente", b =>
                {
                    b.HasOne("TcgWorld.Api.Data.Entities.Carte", "Carte")
                        .WithMany()
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgWorld.Api.Data.Entities.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carte");

                    b.Navigation("Item");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Annonce", b =>
                {
                    b.Navigation("AnnonceCarte");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Bloc", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Collection", b =>
                {
                    b.Navigation("Cartes");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Commande", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Expedition");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("OffresPrix");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Enchere", b =>
                {
                    b.Navigation("EnchereCarte");

                    b.Navigation("Mises");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Jeu", b =>
                {
                    b.Navigation("Blocs");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.OffrePrix", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Panier", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.Serie", b =>
                {
                    b.Navigation("Cartes");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TcgWorld.Api.Data.Entities.TypeItem", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
